AllCops:
  NewCops: enable
  Exclude:
    - vendor/bundle/**/*
    - gemfiles/**/*.gemfile
    - gemfiles/vendor/**/*
    - spec/dummy_engine/dummy_engine.gemspec
    - spec/schemas/**/*.rb

require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-thread_safety
  - rubocop-rake
  - rubocop-rspec

Gemspec/RequiredRubyVersion:
  Exclude:
    - 'ros-apartment.gemspec'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Metrics/ModuleLength:
  Exclude:
    - lib/apartment/patches/**/*.rb

Metrics/MethodLength:
  Max: 20

Rails/RakeEnvironment:
  Enabled: false

Rails/ApplicationRecord:
  Enabled: false

Rails/Output:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/InlineComment:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  Exclude:
    - Gemfile

Style/MethodCallWithArgsParentheses:
  Enabled: true
  EnforcedStyle: require_parentheses
  AllowedPatterns:
    - 'puts'
    - 'info'
    - 'warn'
    - 'debug'
    - 'error'
    - 'fatal'
    - 'fail'

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/ClassAndModuleChildren:
  EnforcedStyle: nested
  AutoCorrect: true

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'detect'
    find_all: 'select'

ThreadSafety/NewThread:
  Exclude:
    - 'spec/shared_examples/*thread_safety_examples.rb'

## Rspec

RSpec/ExampleLength:
  Max: 20

RSpec/IndexedLet:
  AllowedPatterns:
    - 'schema'
    - 'tenant'

RSpec/MultipleExpectations:
  Max: 5

RSpec/MultipleMemoizedHelpers:
  Max: 10