os: linux

language: ruby
services:
  - docker
rvm:
  - jruby-9.2.11.0
  - 2.4.10
  - 2.5.8
  - 2.6.6
  - 2.7.1
  - jruby-head
  - ruby-head

branches:
  only:
    - master
    - development

gemfile:
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_6_0.gemfile
  - gemfiles/rails_master.gemfile

bundler_args: --without local
before_install:
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  - docker-compose up -d

install:
  - gem install --no-document rubocop

before_script:
  - rubocop --version

env:
  RUBY_GC_MALLOC_LIMIT: 90000000
  RUBY_GC_HEAP_FREE_SLOTS: 200000
jobs:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - gemfile: gemfiles/rails_master.gemfile
  exclude:
    - rvm: 2.4.10
      gemfile: gemfiles/rails_6_0.gemfile
  fast_finish: true
cache: bundler
