test:
  adapter: postgresql
  database: <%= ENV.fetch('APARTMENT_TEST_PG_DB', 'apartment_v4_test') %>
  host: <%= ENV.fetch('PGHOST', '127.0.0.1') %>
  port: <%= ENV.fetch('PGPORT', '5432') %>
  username: <%= ENV.fetch('PGUSER', ENV.fetch('USER', nil)) %>
  password: <%= ENV.fetch('PGPASSWORD', nil) %>
  schema_search_path: public
