name: RSpec PostgreSQL 17
on:
  push:
    branches:
      - development
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  release:
    types: [published]

jobs:
  test:
    name: ${{ github.workflow }}, Ruby ${{ matrix.ruby_version }}, Rails ${{ matrix.rails_version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby_version:
          - 3.1
          - 3.2
          - 3.3
          - jruby
        rails_version:
          - 6_1
          - 7_0
          - 7_1
          - 7_2
          # - master # versions failing
        exclude:
          - ruby_version: jruby
            rails_version: 7_1
          - ruby_version: jruby
            rails_version: 7_2
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/rails_${{ matrix.rails_version }}${{ matrix.ruby_version == 'jruby' && '_jdbc' || '' }}_postgresql.gemfile
      CI: true
      DATABASE_ENGINE: postgresql
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_DB: apartment_postgresql_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Install PostgreSQL client
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends lsb-release wget ca-certificates
          sudo wget -O /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc https://www.postgresql.org/media/keys/ACCC4CF8.asc
          sudo sh -c 'echo "deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends postgresql-client-17
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
      - name: Configure config database.yml
        run: bundle exec rake db:load_credentials
      - name: Database Setup
        run: bundle exec rake db:test:prepare
      - name: Run tests
        run: bundle exec rspec --format progress --format RspecJunitFormatter -o ~/test-results/rspec/rspec.xml
